name: Django Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Coverage report
      run: |
        pip install coverage
        coverage run backend/server/endpoints/tests.py
        coverage report
    - name: Django Testing
      run: |
        python3 backend/server/endpoints/test.py
    # - name: Install pytest
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    #   # Run the tests. I'm using pytest and the file is in the tests directory.
    # - name: Run tests
    #   run: pytest backend/server/endpoints/tests.py